- name: Playbook to demonstrate enhanced loops
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Loop through list
      debug:
        msg: "{{ item }}"
      loop:
        - apple
        - banana
        - cherry
