roles:
# Install a role from Ansible Galaxy.
- name: geerlingguy.pip
  version: 2.2.0
- name: geerlingguy.docker
  version: 7.0.1
collections:
# Install a collection from Ansible Galaxy.
- name: devroles.system
  version: 3.0.0
  source: https://galaxy.ansible.com
