---
- hosts: all
  tasks:

  - name: Run container
    command: docker run --rm -v /tmp/hello:/tmp busybox:latest sh -c "echo Hello!"
    register: output
    become: yes

  - name: Show results
    ansible.builtin.debug:
      var: output
