---
- name: Установка Kubernetes
  hosts: k8smaster
  become: yes
  tasks:
    - name: Установка необходимых пакетов
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Установка необходимых утилит
      apt:
        name:
          - conntrack
          - socat
        state: present
        update_cache: yes

    - name: Download crictl
      get_url:
        url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.31.1/crictl-v1.31.1-linux-amd64.tar.gz
        dest: /tmp/crictl.tar.gz
        mode: '0644'

    - name: Extract crictl
      unarchive:
        src: /tmp/crictl.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Set permissions for crictl
      file:
        path: /usr/local/bin/crictl
        mode: '0755'

    - name: Verify crictl installation
      command: crictl --version
      register: crictl_version
      when: ansible_verbosity > 2

    - name: Print crictl version
      debug:
        msg: "crictl version: {{ crictl_version.stdout }}"
      when: ansible_verbosity > 2

    - name: Установка snapd
      apt:
        name: snapd
        state: present

    - name: Установка kubelet, kubeadm и kubectl через snap
      snap:
        name: "{{ item }}"
        state: present
        classic: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Отключение swap
      command: swapoff -a
      ignore_errors: yes

    - name: Инициализация кластера Kubernetes
      command: kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=Port-10250
      register: kubeadm_init

    - name: Настройка kubectl для текущего пользователя
      copy:
        dest: ~/.kube/config
        content: "{{ kubeadm_init.stdout_lines | join('\n') }}"
      when: kubeadm_init.changed

    - name: Установка сетевого плагина (например, Flannel)
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel.yml


    - name: Включение и запуск службы kubelet
      systemd:
        name: snap.kubelet.daemon
        enabled: yes
        state: restarted

