---
- name: Install and configure Nginx
  hosts: nlbs
  become: yes

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Nginx
    apt:
      name: nginx
      state: present
    notify: restart nginx

  - name: Configure Nginx
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: '0644'
    notify: restart nginx

  - name: Create upstream configuration
    template:
      src: templates/upstream.conf.j2
      dest: /etc/nginx/conf.d/upstream.conf
      mode: '0644'
    notify: restart nginx

  - name: Start and enable Nginx
    service:
      name: nginx
      state: started
      enabled: yes

#  - name: Flush handlers
#    meta: flush_handlers

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

  post_tasks:

  - name: Verify httpd response
    uri:
      url: "http://{{ ansible_host }}:80"
      return_content: yes
    register: result
    tags: check

  - name: Print httpd response
    debug:
      var: result.content
    tags: check
