---
- name: Install Ansible on Linux
  hosts: all
  become: no
  gather_facts: no

  tasks:
  - name: Verify Ansible installation
    command: ansible --version
    register: ansible_version
    changed_when: false

  - debug:
     var: ansible_version.string
