---
- name: Print hello message
  hosts: all
  gather_facts: no

  vars_prompt:
    - name: login
      prompt: Enter login
      private: no
    - name: password
      prompt: Enter password
      private: yes

  tasks:
  - name: Print message
    debug:
      msg: "Entered login is {{ login }} password is {{ password }}"
