
variable "ansible_user" {
  type    = string
  default = "ansible"
}

variable "folder_id" {
  type    = string
  default = "${env("YC_FOLDER")}"
}

variable "path_to_key" {
  type    = string
  default = "/home/aleksey/.ssh/id_rsa.pub"
}

variable "token" {
  type    = string
  default = "${env("YC_TOKEN")}"
}

source "yandex" "autogenerated_1" {
  folder_id           = "${var.folder_id}"
  image_family        = "my-ansible-node-family"
  image_name          = "my-ansible-node-image"
  source_image_family = "ubuntu-2204-lts"
  ssh_username        = "ubuntu"
  token               = "${var.token}"
  use_ipv4_nat        = true
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp/key.pub"
    source      = "${var.path_to_key}"
  }

  provisioner "shell" {
    inline = ["sleep 5", "sudo useradd -m -s /bin/bash -G sudo ${var.ansible_user}", "sleep 5", "echo '${var.ansible_user} ALL=(ALL:ALL) NOPASSWD:ALL' > /tmp/ansible_user_sudoer.txt", "sudo cp /tmp/ansible_user_sudoer.txt /etc/sudoers.d/${var.ansible_user}", "sudo chmod 0440 /etc/sudoers.d/${var.ansible_user}", "sudo mkdir /home/${var.ansible_user}/.ssh", "sudo cp /tmp/key.pub /home/${var.ansible_user}/.ssh/authorized_keys"]
  }

}
