---
- name: Установка пакетов для docker_container
  hosts: all
  tasks:

    - name: Установка pip3 если нет
      apt:
        name: python3-pip
        update_cache: yes
      become: yes

    - name: Установка Docker с помощью pip
      pip:
        name: docker

