---
- name: deploy httpd on container
  hosts: all
  vars:
    webroot: "/tmp/webroot/"
  tasks:

    - name: pull image
      community.docker.docker_image:
        name: httpd
        source: pull
        tag: latest

    - name: webroot present
      ansible.builtin.file:
        path: "{{ webroot }}"
        state: directory

    - name: custom index.html
      ansible.builtin.copy:
        dest: "{{ webroot}}index.html"
        content: |
          Custom Web Page from {{inventory_hostname}}

    - name: stop and remove previous container
      community.docker.docker_container:
        name: webserver
        image: httpd
        state: stopped
        auto_remove: yes

    - name: run httpd container
      community.docker.docker_container:
        name: webserver
        image: httpd
        state: started
        detach: true
        auto_remove: yes
        exposed_ports:
          - '80'
        ports:
          - '8080:80'
        volumes: "{{ webroot }}:/usr/local/apache2/htdocs/" 

    - name: Verify httpd response
      uri:
        url: http://{{ansible_host}}:8080
        return_content: yes
      register: result
    - name: Print httpd response
      debug:
        var: result
