---
- name: Install Minikube
  hosts: all

  tasks:
  - name: Download Minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      dest: /tmp/minikube_latest_amd64.deb

  - name: Install Minikube
    command: dpkg -i /tmp/minikube_latest_amd64.deb
    become: yes

  - name: Check Docker
    command: docker ps

  - name: Start Minikube
    command: minikube start

# new tasks need to test:

  - name: get minikube kubectl and interact with the cluster
    command: minikube kubectl -- get po -A
    register: minikube_kubectl_output

  - name: Print minikube kubectl output
    debug:
      var: minikube_kubectl_output.stdout

#  - name: Add kubectl alias to .bashrc
#    lineinfile:
#      path: "~/.bashrc"
#      line: "alias kubectl=\"minikube kubectl --\""
#      state: present

  - name: Enable metrics-server
    command: minikube addons enable metrics-server

  - name: Run minikube addons list command
    command: minikube addons list
    register: addons_output

  - name: Print minikube addons list output
    debug:
      var: addons_output.stdout_lines

  tasks:
  - name: Install snap
    apt:
      name: snapd
      state: present
    # Install snap package manager
    become: yes

  - name: Install kubectl
    shell:
      cmd: "snap install kubectl --classic"
    # Install kubectl using snap with classic confinement
    become: yes

  - name: Verify kubectl installation
    shell:
      cmd: "kubectl version"
    register: kubectl_version
    # Check if kubectl is installed and get its version

  - name: Print kubectl version
    debug:
      msg: "kubectl version: {{ kubectl_version.stdout }}"

  - name: get kubectl and interact with the cluster
    command: kubectl get po -A
    register: kubectl_output

  - name: Print kubectl output
    debug:
      var: kubectl_output.stdout

#  - name: Start minikube dashboard in the background
#    shell: "minikube dashboard --port=3333 --url=true"
#    async: 1
#    poll: 0
#    register: dashboard_output

#  - name: Show minikube dashboard URL
#    debug:
#      var: dashboard_output.stdout_lines



