---
- name: Установка и настройка сервера
  hosts: my_server
  become: yes
  vars:
    mysql_version: 5.7


  tasks:

  - import_tasks: tasks/nginx.yml

  - import_tasks: tasks/mysql.yml
    when: mysql_version is defined



