
FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "app.py"]

...
Healthcheck Instruction Missing, Severity: LOW, Results: 1
...
Missing User Instruction, Severity: HIGH, Results: 1
...




