---
- hosts: sc
#  become: true

  tasks:

    - name: Установить epel-release
      yum:
        name: epel-release
        state: present
        update_cache: yes
      become: true

    - name: Установить s3fs-fuse
      yum:
        name: s3fs-fuse
        state: present
      become: true

    - name: Копировать файл passwd-s3fs.sensitive.plaintext
      copy:
        src: passwd-s3fs.sensitive.plaintext
        dest: ~/.passwd-s3fs
        mode: '0600'
