---
- hosts: sc
#  become: true

  tasks:

#    - name: Установить epel-release
#      yum:
#        name: epel-release
#        state: present
#        update_cache: yes
#      become: true

#    - name: Установить s3fs-fuse
#      yum:
#        name: s3fs-fuse
#        state: present
#      become: true

#    - name: Копировать файл passwd-s3fs.sensitive.plaintext
#      copy:
#        src: passwd-s3fs.sensitive.plaintext
#        dest: ~/.passwd-s3fs
#        mode: '0600'

#    - name: Создать директорию /mount/sc
#      file:
#        path: /mount/sc
#        state: directory
#        mode: '0777'
##        creates: /nount/sc
#      become: true

#    - name: Монтировать S3FS
#      command: s3fs otus-audit-log /mount/sc -o passwd_file=$HOME/.passwd-s3fs -o url=https://storage.yandexcloud.net -o use_path_request_style

    - name: Запустить программу настройки агента
      shell: |
        echo '1'                # Чтобы создать новую конфигурацию, введите значение 1 (create new config).
        echo '3'                # Выберите компонент для настройки – 3 (jsonfolderfollower).
        echo '1'                # Установите источники аудитных логов: Введите значение 1 (Add, modify, or remove sources).
        echo 'A'                # Установите источники аудитных логов:
        echo 'yc'               # в поле config file укажите yc;
        echo '/mount/sc/'       # в поле folder укажите путь к смонтированному бакету с аудитными логами, например /home/agent/logs/;
        echo '*.json'           # в поле wildcard укажите маску логов *.json;
        echo 'R'                # в поле mode укажите, что делать с логами после обработки на ВМ: D (DeleteFile) – удалять или R (RenameFile) – переименовывать;
        echo 'Y'                # в поле process folders recursively введите Y(Yes).
        echo 'F'                # Проверьте указанные параметры и введите F (Finish).
        echo '2'                # Введите значение 2 (Add, modify, or remove destinations).
        echo 'A'                # Выберите опцию A (Add) и задайте параметры получателя:
        echo '0'                # в поле Destination type введите 0 (cefsyslog);
        echo '$DEST_IP'         # в поле Host введите IP-адрес сервера, на котором установлен syslog-коннектор SIEM-системы в вашей корпоративной сети;
        echo '514'              # в поле Port укажите 514;
        echo 'UDP'              # в поле Protocol укажите UDP.
        echo 'F'                # Проверьте указанные параметры и введите F (Finish).
        echo '3'                # ведите значение 3 (Install as a service).
        echo 'N'                # Чтобы изменить имя и описание сервиса, на запрос Change service name/description введите Y (Yes) и задайте новые параметры:
        echo 'Y'                # В строке Starting the service at startup введите Y (Yes).
        echo '0'                # Чтобы выйти из меню конфигурирования, введите значение 0 (Exit).
      args:
        executable: /home/agent/yc_agent/agent agentsetup
        stdin: "yes"
      become: true
