---
- hosts: sc
#  become: true

  tasks:

    - name: Установить epel-release
      yum:
        name: epel-release
        state: present
        update_cache: yes
      become: true

    - name: Установить s3fs-fuse
      yum:
        name: s3fs-fuse
        state: present
      become: true

    - name: Копировать файл passwd-s3fs.sensitive.plaintext
      copy:
        src: passwd-s3fs.sensitive.plaintext
        dest: ~/.passwd-s3fs
        mode: '0600'
#        mode: '0644'
      become: true
      become_user: agent

    - name: Создать директорию /mount/sc
      file:
        path: /mount/sc
        state: directory
        mode: '0777'
#        creates: /nount/sc
      become: true

    - name: Монтировать S3FS
      command: s3fs otus-audit-log /mount/sc -o passwd_file=$HOME/.passwd-s3fs -o url=https://storage.yandexcloud.net -o use_path_request_style
      become: true
      become_user: agent
