# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "jammy64/ansible"
    config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.define "lb" do |server|
    server.vm.host_name = 'loadbalancer'
    server.vm.network :private_network, ip: "192.168.56.6"
    server.vm.network "forwarded_port", guest: 80, host: 8086
    server.vm.provision "shell", inline: "hostname"

    server.vm.provision "file",
      source: "sites-default",
      destination: "/home/vagrant/sites-default"

    server.vm.provision "shell",
      inline: "sudo mv -f /home/vagrant/sites-default /etc/nginx/sites-available/default"

    server.vm.provision "shell",
      inline: "sudo systemctl reload nginx"
  end

  (1..2).each do |i|
    config.vm.define "backend#{i}" do |node|
      node.vm.host_name = "backend#{i}"
      node.vm.network :private_network, ip: "192.168.56.#{6+i}"

      node.vm.provision "shell", inline: <<-SHELL\
        hostname | sudo tee /var/www/html/index.html
      SHELL
    end
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/ansible_local.yml"
  end

end
