
variable "folder_id" {
  type    = string
  default = "${env("YC_FOLDER")}"
}

variable "token" {
  type    = string
  default = "${env("YC_TOKEN")}"
}

source "yandex" "autogenerated_1" {
  folder_id           = "${var.folder_id}"
  image_family        = "my-ws-hello-family"
  image_name          = "my-ws-hello-image"
  source_image_family = "ubuntu-2204-lts"
  ssh_username        = "ubuntu"
  token               = "${var.token}"
  use_ipv4_nat        = true
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30", "sudo apt update", "sleep 30", "sudo apt install -y apache2", "sleep 30", "echo '<html><body><h1>Hello, World!</h1></body></html>' | sudo tee /var/www/html/index.html"]
  }

}
