---
- name: Create /etc/docker/daemon.json file and restart Docker service
  hosts: docker
  become: yes
  tasks:
    - name: Create /etc/docker/daemon.json file
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "userns-remap": "default"
          }
#        validate: 'json'
      notify: Restart Docker service

  handlers:
    - name: Restart Docker service
      service:
        name: docker
        state: restarted
