---
- name: Install and clone Docker Bench Security
  hosts: docker
#  become: yes

  tasks:
  - name: Install git
    apt:
      name: git
      state: present
    become: yes

  - name: Clone Docker Bench Security repository
    git:
      repo: 'https://github.com/docker/docker-bench-security.git'
      dest: ./docker-bench-security
#      version: master
      accept_hostkey: yes
