---
- name: Configure Docker daemon
  hosts: docker
  become: yes

  tasks:
  - name: Create /etc/docker/daemon.json
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      mode: '0644'
    notify: reload docker

  handlers:
  - name: reload docker
    service:
      name: docker
      state: reloaded
