---
- name: Установка и настройка Prometheus
  hosts: prometheus
  become: yes
  vars:
    prometheus_version: "2.54.1"  # Указана версия Prometheus
    prometheus_user: "prometheus"  # Имя пользователя для запуска Prometheus
    prometheus_config_path: "/home/{{ prometheus_user }}/prometheus.yml"
    prometheus_data_dir: "/home/{{ prometheus_user }}/data"
    prometheus_targets: []

  tasks:
    - name: Получение IP-адресов webservers
      set_fact:
        prometheus_targets: "{{ groups['webservers'] | map('extract', hostvars, 'ansible_host') | list }}"

    - name: Создание пользователя для Prometheus
      user:
        name: "{{ prometheus_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Установка необходимых пакетов
      apt:
        name:
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Создание директории для данных Prometheus
      file:
        path: "{{ prometheus_data_dir }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"

    - name: Скачивание Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Распаковка Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/home/{{ prometheus_user }}/"
        remote_src: yes
        extra_opts: [ "--strip-components=1" ]  # Удаляет верхний уровень директории

    - name: Создание конфигурационного файла Prometheus
      copy:
        dest: "{{ prometheus_config_path }}"
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'webservers'
              static_configs:
                - targets: 
                  {% for target in prometheus_targets %}
                    - {{ target }}:8888
                  {% endfor %}

    - name: Создание systemd unit файла для Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          User={{ prometheus_user }}
          ExecStart=/home/{{ prometheus_user }}/prometheus --config.file={{ prometheus_config_path }} --storage.tsdb.path={{ prometheus_data_dir }} --web.listen-address=":9090"

          [Install]
          WantedBy=multi-user.target

    - name: Запуск и включение Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Удаление временного файла
      file:
        path: /tmp/prometheus.tar.gz
        state: absent

