---
- name: Install Minikube
  hosts: all

  tasks:
  - name: Download Minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      dest: /tmp/minikube_latest_amd64.deb

  - name: Install Minikube
    command: dpkg -i /tmp/minikube_latest_amd64.deb
    become: yes

  - name: Check Docker
    command: docker ps

  - name: Start Minikube
    command: minikube start

