---
- name: App
  hosts: app
  become: yes

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  tasks:
  - name: Install Python and MySQL connector
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - python3
      - python3-mysqldb
      - python3-mysql.connector
      - python3-flask

  - name: Create /var/www/html directory
    file:
      path: /var/www/html
      state: directory

  - name: Create a Python script to connect to MySQL
    template:
      src: templates/app.py.j2
      dest: /var/www/html/app.py
      mode: '0644'

  - name: Start Flask app
    command: python3 /var/www/html/app.py
