---
- name: Create VM
  hosts: localhost
  become: no
  gather_facts: no

  vars:
    vmn: 3
    VM_NAME: "ws"
    YC_ZONE: "ru-central1-a"
    YC_GROUP: "webservers"
    YC_IMAGE_ID: "fd8pecdhv50nec1qf9im"
    YC_SUBNET_ID: "e9bop98iu12teftg4uj8"

  tasks:
  - name: Create VM
    command: yc compute instance create \
      --name "{{ VM_NAME }}{{ item }}" \
      --hostname "{{ VM_NAME }}{{ item }}" \
      --zone={{ YC_ZONE }} \
      --labels group={{ YC_GROUP }} \
      --create-boot-disk size=20GB,image-id={{ YC_IMAGE_ID }} \
      --cores=2 \
      --memory=2G \
      --core-fraction=20 \
      --preemptible \
      --network-interface subnet-id={{ YC_SUBNET_ID }},ipv4-address=auto,nat-ip-version=ipv4 \
      --ssh-key ~/.ssh/id_rsa.pub
    register: vm_output
    ignore_errors: yes
    loop: "{{ range(1, vmn + 1) | list }}"


#  - name: Print VM output
#    debug:
#      msg: "{{ vm_output.stdout }}"

  - name: Print VM output
    debug:
      msg: "VM {{ item }}: {{ vm_output.results[item - 1].stdout }}"
    loop: "{{ range(1, vmn + 1) | list }}"

