---
- name: MySQL
  hosts: mysql
  become: yes

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  tasks:
  - name: Install MySQL and PyMySQL
    apt:
      name: mysql-server, python3-pymysql
      state: present

  - name: Configure MySQL
    template:
      src: templates/mysql.cnf.j2
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      mode: '0644'
    notify: restart mysql

  handlers:
  - name: restart mysql
    service:
      name: mysql
      state: restarted

  post_tasks:
#  - name: Create MySQL user
#    mysql_user:
#      name: username
#      password: password
#      host: app.ru-central1.internal
#      priv: '*.*:ALL'
#      state: present
#      login_user: root
#      login_password: ""

#   - name: Create MySQL user
#     mysql_query:
#       query: "CREATE USER 'username'@'%' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'username'@'%'; FLUSH PRIVILEGES;"

   - name: Create MySQL user
     command: "mysql -e \"CREATE USER 'username'@'%' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON *.* TO 'username'@'%'; FLUSH PRIVILEGES;\""
     ignore_errors: yes

   - name: Update MySQL user
     command: "mysql -e \"SET PASSWORD FOR 'username'@'%' = PASSWORD('otherpassword'); GRANT ALL PRIVILEGES ON *.* TO 'username'@'%'; FLUSH PRIVILEGES;\""
     ignore_errors: yes

   - name: Update MySQL user
     command: "mysql -e \"SET PASSWORD FOR 'username'@'%' = PASSWORD('password'); GRANT ALL PRIVILEGES ON *.* TO 'username'@'%'; FLUSH PRIVILEGES;\""
     ignore_errors: yes
