
variable "folder_id" {
  type    = string
  default = "${env("YC_FOLDER")}"
}

variable "pub_key_file" {
  type    = string
  default = "${env("PUB_KEY_FILE")}"
}

variable "subnet_id" {
  type    = string
  default = "${env("YC_SUBNET_ID")}"
}

variable "token" {
  type    = string
  default = "${env("YC_TOKEN")}"
}

variable "zone" {
  type    = string
  default = "${env("YC_ZONE")}"
}

source "yandex" "autogenerated_1" {
  folder_id           = "${var.folder_id}"
  image_family        = "my-ws-hello-family"
  image_name          = "my-ws-hello-image"
  source_image_family = "ubuntu-2204-lts"
  ssh_username        = "ubuntu"
  token               = "${var.token}"
  use_ipv4_nat        = true
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 5", "# sudo apt-get update", "sleep 5", "sudo apt-get install -y apache2", "sleep 5", "echo '<html><body><h1>Hello, World!</h1></body></html>' | sudo tee /var/www/html/index.html"]
  }

  post-processor "yandex-export" {
    keep_input_artifact = true
    folder_id           = "${var.folder_id}"
    paths               = ["s3://otusiacles02/my-exported-image.qcow2", "s3://otusiacles02/template-supported-get-${build.ImageID}-right-here.qcow2"]
    service_account_id  = "ajenudjqt9nn9lct6ij1"
    subnet_id           = "${var.subnet_id}"
    token               = "${var.token}"
  }
}
